import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next+ App",
	description: "Generated by create-next-plus",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<TRPCReactProvider cookies={cookies().toString()}>
					{children}
				</TRPCReactProvider>
			</body>
		</html>
	);
}
